name: joljak-frontend-build
on: 
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - msater

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Build 
        run: npm run build
        
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: 프론트엔드 CI 알림 봇
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.FRONT_DEV_CI_SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.